PIDEV-FRONTEND/PIDEV-FRONTEND/Models/AppUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PIDEV_FRONTEND.Models
{
    public class AppUser
    {
        public int userId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string adress { get; set; }
        public int phoneNumber { get; set; }
        public string aboutMe { get; set; }
        public string profilePic { get; set; }

    }
}

PIDEV-FRONTEND/PIDEV-FRONTEND/Models/LoginForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PIDEV_FRONTEND.Models
{
    public class LoginForm
    {
        public string email { get; set; }
        public string password { get; set; }
    }
}

PIDEV-FRONTEND/PIDEV-FRONTEND/Controllers/AppUserController.cs
using PIDEV_FRONTEND.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace PIDEV_FRONTEND.Controllers
{
    public class AppUserController : Controller
    {
        // GET: AppUser
        public ActionResult Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8081");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("admin/users").Result;
            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<AppUser>>().Result;
            }
            else
            {
                ViewBag.result = "error";
            }
            ViewBag.signup = "";
            ViewBag.signin = "";
            return View("home");
        }

        // GET: AppUser/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AppUser/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AppUser/Create
        [HttpPost]
        public ActionResult Create(string firstName, string lastName, string password, string email)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8081");
            AppUser user = new AppUser();
            user.email = email;
            user.firstName = firstName;
            user.lastName = lastName;
            user.password = password;
            client.PostAsJsonAsync<AppUser>("registerApi/Signup", user).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());
            ViewBag.signup = "Sign up successful";
            return View("home");
        }

        // GET: AppUser/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AppUser/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AppUser/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AppUser/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> LoginAsync(string email, string password)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8081");
            LoginForm log = new LoginForm();
            log.email = email;
            log.password = password;
            String invalidCredentials = "";

            HttpResponseMessage response = await client.PostAsJsonAsync<LoginForm>("login", log).ContinueWith((postTask) => postTask.Result);
            if (response.IsSuccessStatusCode)
            {
                var jwtEncodedString = response.Headers.GetValues("Authorization").First();
                var token = new JwtSecurityToken(jwtEncodedString: jwtEncodedString);
                string jemail = token.Claims.First(c => c.Type == "sub").Value;
                string roles = token.Claims.First(c => c.Type == "roles").Value;
                HttpCookie userCookie = new HttpCookie("Token", jwtEncodedString);
                userCookie.Expires.AddDays(10);
                HttpContext.Response.SetCookie(userCookie);
                HttpCookie newCookie = Request.Cookies["Token"];
                Console.WriteLine(newCookie.Value);

            }
            else
            {
                invalidCredentials = "Invalid Credentials";
                ViewBag.err = invalidCredentials;
                return View("home");
            }
            return View("home");
        }
        public ActionResult Logout()
        {
            if (HttpContext.Request.Cookies.AllKeys.Contains("Token"))
            {
                Request.Cookies["Token"].Expires = DateTime.Now.AddYears(-1);
                HttpContext.Response.SetCookie(Request.Cookies["Token"]);
            }

            return RedirectToAction("home");
        }
        public ActionResult addPropertyView()
        {
            return View();
        }
        public ActionResult home()
        {
            ViewBag.user = this.currentUser();
            return View();
        }
        public async System.Threading.Tasks.Task<ActionResult> AddAnnouncementAsync(string estateType, string location, double price)
        {
            Announcement ann = new Announcement();
            ann.estateType = estateType;
            ann.location = location;
            ann.price = price;
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8081");
            string jwtEncodedString = Request.Cookies["Token"].Value;
            Debug.WriteLine(jwtEncodedString);
            // var token = new JwtSecurityToken(jwtEncodedString: jwtEncodedString);

            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", jwtEncodedString);
            HttpResponseMessage response = await client.PostAsJsonAsync<Announcement>("apiHF/addAnnounce", ann).ContinueWith((postTask) => postTask.Result);
            if (response.IsSuccessStatusCode)
            {
                ViewBag.status = response.StatusCode;
                ViewBag.auth = client.DefaultRequestHeaders.Authorization;
            }
            else
            {
                ViewBag.status = response.StatusCode;
                ViewBag.auth = client.DefaultRequestHeaders.Authorization;
                Debug.WriteLine(response.ToString());
                Debug.WriteLine(client.DefaultRequestHeaders.Authorization);
                Debug.WriteLine(location);
                Debug.WriteLine(estateType);
                Debug.WriteLine(price);
            }
            return View("home");
        }

        public async System.Threading.Tasks.Task<string> usernameAsync()
        {
            string jwtEncodedString = Request.Cookies["Token"].Value;
            string username = "";
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8081");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", jwtEncodedString);
            HttpResponseMessage response = client.GetAsync("userapi/loggedInUsername").Result;
            if (response.IsSuccessStatusCode)
            {
                username = await response.Content.ReadAsStringAsync();

            }
            return username;
        }
        public AppUser currentUser()
        {
            AppUser user = new AppUser();
            if (HttpContext.Request.Cookies.AllKeys.Contains("Token"))
            {
                string jwtEncodedString = Request.Cookies["Token"].Value;
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri("http://localhost:8081");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", jwtEncodedString);
                HttpResponseMessage response = client.GetAsync("userapi/currentUser").Result;
                if (response.IsSuccessStatusCode)
                {
                    user = response.Content.ReadAsAsync<AppUser>().Result;
                }

            }
            return user;
        }
        public ActionResult profile()
        {
            ViewBag.user = this.currentUser();
            return View();
        }
        public ActionResult dashboard()
        {
            ViewBag.user = this.currentUser();
            return View();
        }
        public ActionResult bookmarks()
        {


            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8081");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            string jwtEncodedString = Request.Cookies["Token"].Value;
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", jwtEncodedString);
            HttpResponseMessage response = client.GetAsync("apiHF/Favourites").Result;

            ViewBag.favourites = response.Content.ReadAsAsync<IEnumerable<Announcement>>().Result;

            ViewBag.user = this.currentUser();
            return View();
        }
        public ActionResult myproperty()
        {
            ViewBag.user = this.currentUser();
            return View();
        }
        public ActionResult submitPropertyDashboard()
        {
            ViewBag.user = this.currentUser();
            return View();
        }
        public ActionResult changePassword()
        {
            ViewBag.user = this.currentUser();
            return View();
        }
        public ActionResult updateProfile(string firstName, string lastName, string email, int phoneNumber, string adress, string aboutMe)
        {
            AppUser user = new AppUser();
            if (firstName != null)
            { user.firstName = firstName; }
            if (lastName != null)
            { user.lastName = lastName; }
            if (email != null)

PIDEV-FRONTEND/PIDEV-FRONTEND/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PIDEV_FRONTEND.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PIDEV-FRONTEND/PIDEV-FRONTEND/Views/AppUser/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <a href="@Url.Action("Create","AppUser")">add new user</a>
    <table cellpadding="2" cellspacing="2" border="1">
        <tr>
            <th>id</th>
            <th>email</th>
            <th>password</th>
            <th>firstName</th>
            <th>lastName</th>
        </tr>
        @foreach (var p in ViewBag.result)
        {
    <tr>
        <th>@p.userId</th>
        <th>@p.email</th>
        <th>@p.password</th>
        <th>@p.firstName</th>
        <th>@p.lastName</th>
    </tr>
        }

    </table>
</body>
</html>

PIDEV-FRONTEND/PIDEV-FRONTEND/Views/AppUser/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}

PIDEV-FRONTEND/PIDEV-FRONTEND/Views/AppUser/Logout.cshtml
@{
    ViewBag.Title = "Logout";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}

PIDEV-FRONTEND/PIDEV-FRONTEND/Views/AppUser/bookmarks.cshtml
@{
    ViewBag.Title = "bookmarks";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}
<!-- ============================ Page Title Start================================== -->
<div class="page-title">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <h2 class="ipt-title">Welcome!</h2>
                <span class="ipn-subtitle">Welcome To Your Account</span>

            </div>
        </div>
    </div>
</div>
<!-- ============================ Page Title End ================================== -->
<!-- ============================ User Dashboard ================================== -->
<section class="bg-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="filter_search_opt">
                    <a href="javascript:void(0);" onclick="openFilterSearch()">Dashboard Navigation<i class="ml-2 ti-menu"></i></a>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-lg-3 col-md-12">

                <div class="simple-sidebar sm-sidebar" id="filter_search">

                    <div class="search-sidebar_header">
                        <h4 class="ssh_heading">Close Filter</h4>
                        <button onclick="closeFilterSearch()" class="w3-bar-item w3-button w3-large"><i class="ti-close"></i></button>
                    </div>

                    <div class="sidebar-widgets">
                        <div class="dashboard-navbar">

                            <div class="d-user-avater">

                                <img src="~/Content/img/profileImages/@ViewBag.user.profilePic" class="img-fluid avater" alt="#">
                                <h4>@ViewBag.user.firstName @ViewBag.user.lastName</h4>
                            </div>

                            <div class="d-navigation">
                                <ul>
                                    <li><a href="~/AppUser/dashboard"><i class="ti-dashboard"></i>Dashboard</a></li>
                                    <li class="active"><a href="~/AppUser/profile"><i class="ti-user"></i>My Profile</a></li>
                                    <li><a href="~/AppUser/bookmarks"><i class="ti-bookmark"></i>Bookmarked Listings</a></li>
                                    <li><a href="~/AppUser/myproperty"><i class="ti-layers"></i>My Properties</a></li>
                                    <li><a href="~/AppUser/submitPropertyDashboard"><i class="ti-pencil-alt"></i>Submit New Property</a></li>
                                    <li><a href="~/AppUser/changePassword"><i class="ti-unlock"></i>Change Password</a></li>
                                    <li><a href="#"><i class="ti-power-off"></i>Log Out</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>

                </div>
            </div>

            <div class="col-lg-9 col-md-12">
                <div class="dashboard-wraper">

                    <!-- Bookmark Property -->
                    <div class="form-submit">
                        <h4>Bookmark Property</h4>
                    </div>

                    <table class="property-table-wrap responsive-table bkmark">

                        <tbody>
                            <tr>
                                <th><i class="fa fa-file-text"></i> Property</th>
                                <th></th>
                            </tr>
                            @if (ViewBag.favourites != null)
                            {
                                foreach (var item in ViewBag.favourites)
                            {
                                    <tr>
                                        <td class="property-container">
                                            <img src="~/Content/img/p-2.jpg" alt="">
                                            <div class="title">
                                                <h4><a href="#">property name</a></h4>
                                                <span>@item.location</span>
                                                <span class="table-property-price">@item.price</span>
                                            </div>
                                        </td>
                                        <td class="action">
                                            <a href="@Url.Action("deleteFromFavourite", "AppUser", new { announcementId = @item.announcementId})" class="delete"><i class="ti-close"></i> Delete</a>
                                        </td>
                                    </tr>
                            }
                            }




                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </div>
</section>
<!-- ============================ User Dashboard End ================================== -->
<!-- ============================ Call To Action ================================== -->
<section class="theme-bg call-to-act-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                <div class="call-to-act">
                    <div class="call-to-act-head">
                        <h3>Want to Become a Real Estate Agent?</h3>
                        <span>We'll help you to grow your career and growth.</span>
                    </div>
                    <a href="#" class="btn btn-call-to-act">SignUp Today</a>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- ============================ Call To Action End ================================== -->

PIDEV-FRONTEND/PIDEV-FRONTEND/Views/AppUser/changePassword.cshtml
@{
    ViewBag.Title = "changePassword";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}
<!-- ============================ Page Title Start================================== -->
<script>
 function showPwd(id, el) {
  let x = document.getElementById(id);
  if (x.type === "password") {
    x.type = "text";
    el.className = 'fa fa-eye-slash showpwd';
  } else {
    x.type = "password";
    el.className = 'fa fa-eye showpwd';
  }
    }
    
</script>

<div class="page-title">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <h2 class="ipt-title">Welcome!</h2>
                <span class="ipn-subtitle">Welcome To Your Account</span>

            </div>
        </div>
    </div>
</div>
<!-- ============================ Page Title End ================================== -->
<!-- ============================ User Dashboard ================================== -->
<section class="bg-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="filter_search_opt">
                    <a href="javascript:void(0);" onclick="openFilterSearch()">Dashboard Navigation<i class="ml-2 ti-menu"></i></a>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-lg-3 col-md-12">

                <div class="simple-sidebar sm-sidebar" id="filter_search">

                    <div class="search-sidebar_header">
                        <h4 class="ssh_heading">Close Filter</h4>
                        <button onclick="closeFilterSearch()" class="w3-bar-item w3-button w3-large"><i class="ti-close"></i></button>
                    </div>

                    <div class="sidebar-widgets">
                        <div class="dashboard-navbar">

                            <div class="d-user-avater">

                                <img src="~/Content/img/profileImages/@ViewBag.user.profilePic" class="img-fluid avater" alt="#">
                                <h4>@ViewBag.user.firstName @ViewBag.user.lastName</h4>
                            </div>

                            <div class="d-navigation">
                                <ul>
                                    <li><a href="~/AppUser/dashboard"><i class="ti-dashboard"></i>Dashboard</a></li>
                                    <li class="active"><a href="~/AppUser/profile"><i class="ti-user"></i>My Profile</a></li>
                                    <li><a href="~/AppUser/bookmarks"><i class="ti-bookmark"></i>Bookmarked Listings</a></li>
                                    <li><a href="~/AppUser/myproperty"><i class="ti-layers"></i>My Properties</a></li>
                                    <li><a href="~/AppUser/submitPropertyDashboard"><i class="ti-pencil-alt"></i>Submit New Property</a></li>
                                    <li><a href="~/AppUser/changePassword"><i class="ti-unlock"></i>Change Password</a></li>
                                    <li><a href="#"><i class="ti-power-off"></i>Log Out</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>

                </div>
            </div>

            <div class="col-lg-9 col-md-12">
                <div class="dashboard-wraper">

                    <!-- Basic Information -->
                    @using (Html.BeginForm("changePassword", "AppUser"))
                    {
                    <div class="form-submit">
                        <h4>Change Your Password</h4>
                        <div class="submit-section">
                            <div class="row">

                                <div class="form-group col-lg-12 col-md-6">
                                    <label>Old Password</label>
                                    <input type="password" class="form-control" name="old" id="old">
                                    <i class="fa fa-eye showpwd" onClick="showPwd('old', this)"></i>
                                </div>

                                <div class="form-group col-md-6">
                                    <label>New Password</label>
                                    <input type="password" class="form-control" name="newPass" id="passwd">
                                    <i class="fa fa-eye showpwd" onClick="showPwd('passwd', this)"></i>
                                </div>

                                <div class="form-group col-md-6">
                                    <label>Confirm password</label>
                                    <input type="password" class="form-control" name="newPassConfirm" id="newpwd">
                                    <i class="fa fa-eye showpwd" onClick="showPwd('newpwd', this)"></i>
                                </div>

                                <div class="form-group col-lg-12 col-md-12">
                                    <button class="btn btn-theme-light-2 rounded" type="submit">Save Changes</button>
                                </div>

                            </div>
                        </div>
                    </div>
                    }

                </div>
            </div>

        </div>
    </div>
</section>
<!-- ============================ User Dashboard End ================================== -->
<!-- ============================ Call To Action ================================== -->
<section class="theme-bg call-to-act-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">

                <div class="call-to-act">
                    <div class="call-to-act-head">
                        <h3>Want to Become a Real Estate Agent?</h3>
                        <span>We'll help you to grow your career and growth.</span>
                    </div>
                    <a href="#" class="btn btn-call-to-act">SignUp Today</a>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- ============================ Call To Action End ================================== -->